### ISSUE TITLE
你的睡眠唤醒有问题吗？

### ISSUE THREAD

**Issue by unyielding2013** [VidocqH/Hackintosh-EFI-E3-1230v3-RX580#1]
我的主板是华擎b85m pro4，和你的差不多，用了EFI-10.15.2-Clover，睡眠后唤醒外接显示器黑屏，只能重启电脑。如果使用opencore11不能引导，问题出在哪？先谢谢你的分享。

**Comment by VidocqH** [comment]
妈耶，我刚去试了下发现休眠后我也黑屏了。因为我台式机一直是设置里直接关掉睡眠的，三年下来也没碰上这问题😂。OpenCore不能引导的话得看你问题出在哪个步骤。
